#!/usr/bin/env bash
# Dump a self-contained SQL seed (schema + filtered data) for the tables
# database.go reads, so pkg/database_test.go's live-DB test can run against a
# disposable MySQL container (e.g. in CI) instead of the real internal DB.
#
# Usage: dump_db_seed.sh <host> <user> <pass> <dbname> <run> <output.sql>
# e.g.:  dump_db_seed.sh <internal-db-host> <user> <pass> HDDEMODB 616 \
#            pkg/testdata/hddemo_616_seed.sql
# Run against the real source DB (credentials not stored here) only when
# regenerating the fixture; the output file itself contains no credentials.
set -euo pipefail

HOST=$1; USER=$2; PASS=$3; DB=$4; RUN=$5; OUT=$6

TABLES=(ChannelMapping ChannelPosition FecElecIDBase HuffmanCodesPmt HuffmanCodesSipm)

{
    echo "-- Seed data for $DB, run $RUN."
    echo "-- Generated by scripts/dump_db_seed.sh; do not edit by hand."
    docker run --rm mysql:8.0 mysqldump -h "$HOST" -u "$USER" -p"$PASS" \
        --no-data --compact --skip-comments \
        "$DB" "${TABLES[@]}" 2>/dev/null
    docker run --rm mysql:8.0 mysqldump -h "$HOST" -u "$USER" -p"$PASS" \
        --no-create-info --compact --skip-comments \
        --where="MinRun<=$RUN AND MaxRun>=$RUN" \
        "$DB" "${TABLES[@]}" 2>/dev/null
} > "$OUT"

echo "wrote $OUT"
